### PR TITLE
Add MineSweeper (JS/HTML)

### PR DESCRIPTION
**Pull request by lenard123**

### CODE REVIEW

**Review by nimishbongale — COMMENTED** [review]
Can we move this into the Task 1 folder?

**Comment by lenard123** [comment]
Sorry I put it on the wrong folder, I have fixed it on my latest commit.

**Comment by nimishbongale** [comment]
Can we also add a question.md file as the README.md states?

**Comment by lenard123** [comment]
Question.md Added

**Review by nimishbongale — APPROVED** [review]
Thanks for your contribution! 🚀

**Pull request merged**
