### PR TITLE
Leetcode Python Problem

### PR DESCRIPTION
**Pull request by Karssido**

### CODE REVIEW

**Comment by Karssido** [comment]
Please merge it under the label Hacktoberfest

**Review by nimishbongale — CHANGES_REQUESTED** [review]
Small changes requested, do have a look! 😄

**Comment by Rakteem007** [comment]
Can I contribute to this issue

**Comment by nimishbongale** [comment]
> Can I contribute to this issue

Hey Rakteem, this repo is not participating n Hacktoberfest 2022. You can refer to this issue here:

https://github.com/chandrikadeb7/Hacktoberfest_2021/issues/326

Meanwhile, if you still wish to contribute, you can still do so!

**Pull request closed without merging**
