### PR TITLE
sum of pair of 2 num in an array = x

### PR DESCRIPTION
**Pull request by AtmegaBuzz**
added time complexity analysis with different sorting algorithms

### CODE REVIEW

**Comment by AtmegaBuzz** [comment]
for issue: Find Pair sum in an array Problem

**Comment by Roshan5401** [comment]
Please assign me this problem

**Review by nimishbongale — CHANGES_REQUESTED** [review]
Can we move this into the task 3 folder?

**Comment by nimishbongale** [comment]
Closing this PR due to inactivity, feel free to reopen it 😄

**Pull request closed without merging**
